# Generated by Django 2.2.7 on 2020-04-17 05:12

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('cat_id', models.AutoField(primary_key=True, serialize=False)),
                ('cat_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='College',
            fields=[
                ('col_id', models.AutoField(primary_key=True, serialize=False)),
                ('col_name', models.CharField(max_length=200)),
                ('col_address', models.CharField(max_length=200)),
                ('col_img', models.ImageField(upload_to='media/')),
                ('col_city', models.CharField(max_length=200)),
                ('col_email', models.EmailField(max_length=254)),
                ('col_contact', models.ImageField(upload_to='')),
                ('col_rank', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_id', models.AutoField(primary_key=True, serialize=False)),
                ('course_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Registation',
            fields=[
                ('r_id', models.AutoField(primary_key=True, serialize=False)),
                ('student_first_name', models.CharField(max_length=200)),
                ('student_last_name', models.CharField(max_length=200)),
                ('student_address', models.CharField(max_length=200)),
                ('student_email', models.EmailField(max_length=254)),
                ('student_contact', models.IntegerField()),
                ('student_password', models.CharField(max_length=200)),
                ('registation_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('student_college_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admission.College')),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('d_id', models.AutoField(primary_key=True, serialize=False)),
                ('marksit', models.ImageField(upload_to='media/')),
                ('admit_card', models.ImageField(upload_to='media/')),
                ('adhar_card', models.ImageField(default='', upload_to='media/')),
                ('csc_or_slc', models.ImageField(upload_to='media/')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admission.Registation')),
            ],
        ),
        migrations.CreateModel(
            name='Admission',
            fields=[
                ('admission_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('student_img', models.ImageField(upload_to='media')),
                ('genger', models.CharField(choices=[('Male', 'Male'), ('Fmale', 'Female'), ('Other', 'Other')], max_length=200)),
                ('corrspondance_address', models.CharField(max_length=200)),
                ('current_address', models.CharField(max_length=200)),
                ('pass_out_class', models.CharField(max_length=200)),
                ('passing_year', models.IntegerField(default=0)),
                ('prasent_of_mark', models.IntegerField(default=0)),
                ('admision_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('admision_in_col', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admission.College')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admission.Category')),
                ('couse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admission.Course')),
                ('registation_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admission.Registation')),
            ],
        ),
    ]
