# Generated by Django 2.2.7 on 2020-04-18 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Director',
            fields=[
                ('dir_id', models.AutoField(primary_key=True, serialize=False)),
                ('dir_name', models.CharField(max_length=200)),
                ('dir_email', models.EmailField(max_length=254)),
                ('dir_password', models.CharField(max_length=200)),
                ('dir_contact', models.IntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='registation',
            name='student_email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
