# Generated by Django 2.2.7 on 2020-04-18 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0002_auto_20200417_2138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='college',
            name='col_contact',
            field=models.IntegerField(default=0),
        ),
    ]
