# Generated by Django 2.2.7 on 2020-03-05 14:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Emplyee',
            fields=[
                ('emp_id', models.AutoField(primary_key=True, serialize=False)),
                ('emp_name', models.CharField(max_length=200)),
                ('contact', models.IntegerField()),
                ('emp_gender', models.CharField(choices=[('M', 'MALE'), ('F', 'FEMALE'), ('O', 'OTHER')], max_length=200)),
                ('emp_dob', models.DateField()),
                ('emp_image', models.ImageField(upload_to='media/')),
                ('emp_address', models.CharField(max_length=200)),
                ('emp_city', models.CharField(max_length=200)),
                ('emp_email', models.EmailField(max_length=254)),
                ('emp_password', models.CharField(max_length=200)),
                ('emp_join_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pro_name', models.CharField(max_length=200)),
                ('pro_code', models.IntegerField()),
                ('pro_retail_price', models.IntegerField()),
                ('pro_wholesale_price', models.IntegerField()),
            ],
        ),
    ]
