# Generated by Django 2.2.7 on 2020-03-09 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopwork', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DirSignup',
            fields=[
                ('dir_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('email_id', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='emplyee',
            name='emp_gender',
            field=models.CharField(choices=[('MALE', 'MALE'), ('FEMALE', 'FEMALE'), ('OTHER', 'OTHER')], max_length=200),
        ),
    ]
