# Generated by Django 2.2.7 on 2020-03-17 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopwork', '0002_auto_20200308_2120'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('cont_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('first_contact', models.IntegerField(default=0)),
                ('sec_contact', models.IntegerField(default=0)),
                ('email', models.EmailField(default=0, max_length=254)),
                ('address', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
            ],
        ),
    ]
