# Generated by Django 2.2.7 on 2020-03-17 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopwork', '0003_contact'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
